'use client';

import { useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { db } from '@/lib/db';
import { SyncService } from '@/services/SyncService';
import { ArrowLeft, Users, Plus, CheckCircle2, Circle, Trophy, Calendar, IndianRupee } from 'lucide-react';
import Link from 'next/link';

export default function KametiManagerPage() {
  const [showCreate, setShowCreate] = useState(false);
  const [name, setName] = useState('');
  const [poolAmount, setPoolAmount] = useState('');
  const [membersStr, setMembersStr] = useState('');
  const [startDate, setStartDate] = useState(new Date().toISOString().split('T')[0]);

  const [selectedKametiId, setSelectedKametiId] = useState<string | null>(null);

  const kametis = useLiveQuery(() => db.kametis.reverse().toArray(), []) || [];
  const payments = useLiveQuery(
    () => selectedKametiId ? db.kametiPayments.where('kametiId').equals(selectedKametiId).toArray() : [],
    [selectedKametiId]
  ) || [];

  const handleCreateKameti = async () => {
    const memberNames = membersStr.split(',').map(m => m.trim()).filter(Boolean);
    if (!name || !poolAmount || memberNames.length < 2) return;

    const pool = Number(poolAmount);
    const count = memberNames.length;
    const perMember = Math.round(pool / count);
    
    // UUID will be auto-generated by our Dexie hook, but we need it now to link payments
    const kametiSyncId = crypto.randomUUID();

    await db.kametis.add({
      syncId: kametiSyncId,
      name,
      poolAmount: pool,
      perMemberAmount: perMember,
      memberCount: count,
      startDate,
      members: memberNames,
      createdAt: new Date(),
    });

    // Create payment slots for all members for all months
    const paymentRecords = [];
    for (let month = 1; month <= count; month++) {
      for (const member of memberNames) {
        paymentRecords.push({
          syncId: crypto.randomUUID(),
          kametiId: kametiSyncId,
          memberName: member,
          monthNumber: month,
          isPaid: false,
        });
      }
    }
    await db.kametiPayments.bulkAdd(paymentRecords);
    
    SyncService.sync();
    setShowCreate(false);
    setName(''); setPoolAmount(''); setMembersStr('');
  };

  const togglePayment = async (paymentId: number, currentStatus: boolean) => {
    await db.kametiPayments.update(paymentId, { 
      isPaid: !currentStatus, 
      paidAt: !currentStatus ? new Date() : undefined 
    });
    SyncService.sync();
  };

  const selectedKameti = kametis.find(k => k.syncId === selectedKametiId);

  return (
    <main className="flex-1 flex flex-col bg-gray-50 min-h-screen pb-20">
      <header className="bg-gradient-to-r from-emerald-600 to-teal-600 text-white p-4 shadow-lg sticky top-0 z-10 flex justify-between items-center">
        <div className="flex items-center gap-3">
          <Link href="/" className="p-2 hover:bg-white/15 rounded-full transition-colors">
            <ArrowLeft className="w-6 h-6" />
          </Link>
          <h1 className="text-xl font-bold flex items-center gap-2">
            <Users className="w-5 h-5" /> Digital Kameti
          </h1>
        </div>
        {!selectedKametiId && (
          <button onClick={() => setShowCreate(true)} className="p-2 bg-white/20 hover:bg-white/30 rounded-full">
            <Plus className="w-5 h-5" />
          </button>
        )}
      </header>

      <div className="p-4 max-w-2xl w-full mx-auto flex flex-col gap-6 mt-2">

        {/* List View */}
        {!selectedKametiId && (
          <div className="flex flex-col gap-4">
            {kametis.length === 0 ? (
              <div className="text-center p-10 bg-white rounded-3xl border border-dashed border-emerald-200">
                <Users className="w-12 h-12 text-emerald-300 mx-auto mb-3" />
                <h3 className="font-bold text-gray-700">No Kametis Found</h3>
                <p className="text-sm text-gray-500 mt-1">Start your first digital committee to track payments with absolute zero confusion.</p>
                <button onClick={() => setShowCreate(true)} className="mt-4 bg-emerald-600 text-white font-bold px-6 py-3 rounded-full shadow-lg shadow-emerald-200">
                  + Start New Kameti
                </button>
              </div>
            ) : (
              kametis.map(k => (
                <div key={k.id} onClick={() => setSelectedKametiId(k.syncId!)} className="bg-white p-5 rounded-3xl shadow-sm border border-gray-100 cursor-pointer hover:shadow-md transition-all">
                  <div className="flex justify-between items-start">
                    <div>
                      <h3 className="font-bold text-lg text-gray-800">{k.name}</h3>
                      <p className="text-sm text-gray-500 flex items-center gap-1 mt-1">
                        <Users className="w-4 h-4" /> {k.memberCount} Members • {k.memberCount} Months
                      </p>
                    </div>
                    <div className="text-right">
                      <p className="text-emerald-600 font-bold text-lg">Rs {k.poolAmount.toLocaleString()}</p>
                      <p className="text-xs text-gray-400">Total Pool</p>
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>
        )}

        {/* Detail View */}
        {selectedKameti && (
          <div className="flex flex-col gap-6">
            <button onClick={() => setSelectedKametiId(null)} className="text-emerald-600 font-bold text-sm flex items-center gap-1 -mb-2">
              <ArrowLeft className="w-4 h-4" /> Back to all Kametis
            </button>

            <div className="bg-gradient-to-br from-emerald-600 to-teal-700 p-6 rounded-3xl text-white shadow-lg shadow-emerald-200">
              <h2 className="text-2xl font-bold">{selectedKameti.name}</h2>
              <div className="flex justify-between items-end mt-4">
                <div>
                  <p className="text-emerald-100 text-sm">Monthly Installment</p>
                  <p className="font-bold text-xl">Rs {selectedKameti.perMemberAmount.toLocaleString()} / person</p>
                </div>
                <div className="text-right">
                  <p className="text-emerald-100 text-sm">Total Pool</p>
                  <p className="font-bold text-xl">Rs {selectedKameti.poolAmount.toLocaleString()}</p>
                </div>
              </div>
            </div>

            {/* Months Tracking */}
            <div className="flex flex-col gap-8">
              {Array.from({ length: selectedKameti.memberCount }).map((_, i) => {
                const monthNum = i + 1;
                const monthPayments = payments.filter(p => p.monthNumber === monthNum);
                const payoutReceiver = selectedKameti.members[i]; // Order decides who gets payout
                
                return (
                  <div key={monthNum} className="bg-white rounded-3xl border border-gray-100 shadow-sm overflow-hidden">
                    <div className="bg-gray-50 p-4 border-b border-gray-100 flex justify-between items-center">
                      <h3 className="font-bold text-gray-800 flex items-center gap-2">
                        <Calendar className="w-5 h-5 text-emerald-500" /> Month {monthNum}
                      </h3>
                      <div className="bg-amber-100 text-amber-700 px-3 py-1 rounded-full text-xs font-bold flex items-center gap-1">
                        <Trophy className="w-3 h-3" /> Payout: {payoutReceiver}
                      </div>
                    </div>
                    
                    <div className="p-4 flex flex-col gap-3">
                      {monthPayments.map(p => (
                        <div key={p.id} className="flex justify-between items-center">
                          <span className={\ont-medium \\}>
                            {p.memberName} {p.memberName === payoutReceiver && '(Receiver)'}
                          </span>
                          
                          <button 
                            onClick={() => togglePayment(p.id!, p.isPaid)}
                            className={\lex items-center gap-2 px-4 py-2 rounded-xl text-sm font-bold transition-colors \\}
                          >
                            {p.isPaid ? <CheckCircle2 className="w-4 h-4" /> : <Circle className="w-4 h-4" />}
                            {p.isPaid ? 'Paid' : 'Pending'}
                          </button>
                        </div>
                      ))}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </div>

      {/* Create Modal */}
      {showCreate && (
        <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-3xl w-full max-w-md p-6 flex flex-col gap-4 shadow-2xl animate-in zoom-in-95">
            <h2 className="text-xl font-bold text-gray-800 flex items-center gap-2">
              <Users className="w-6 h-6 text-emerald-500" /> Start New Kameti
            </h2>
            
            <div>
              <label className="text-xs font-bold text-gray-500 uppercase mb-1 block">Kameti Name</label>
              <input type="text" value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Office Kameti 2026" className="w-full bg-gray-50 border border-gray-200 rounded-xl p-3 outline-none focus:border-emerald-500" />
            </div>

            <div>
              <label className="text-xs font-bold text-gray-500 uppercase mb-1 block">Total Pool Amount (Rs)</label>
              <input type="number" value={poolAmount} onChange={e => setPoolAmount(e.target.value)} placeholder="e.g. 100000" className="w-full bg-gray-50 border border-gray-200 rounded-xl p-3 outline-none focus:border-emerald-500" />
            </div>

            <div>
              <label className="text-xs font-bold text-gray-500 uppercase mb-1 block">Members (Comma separated, in payout order)</label>
              <textarea 
                value={membersStr} 
                onChange={e => setMembersStr(e.target.value)} 
                placeholder="Ali, Sara, Usman, Ahmed..." 
                className="w-full bg-gray-50 border border-gray-200 rounded-xl p-3 outline-none focus:border-emerald-500 min-h-[80px]" 
              />
              <p className="text-xs text-gray-400 mt-1">First name gets month 1 payout, second gets month 2, etc.</p>
            </div>

            <div>
              <label className="text-xs font-bold text-gray-500 uppercase mb-1 block">Start Date</label>
              <input type="date" value={startDate} onChange={e => setStartDate(e.target.value)} className="w-full bg-gray-50 border border-gray-200 rounded-xl p-3 outline-none focus:border-emerald-500" />
            </div>

            <div className="flex gap-3 mt-4">
              <button onClick={() => setShowCreate(false)} className="flex-1 py-4 font-bold text-gray-600 bg-gray-100 rounded-xl">Cancel</button>
              <button onClick={handleCreateKameti} className="flex-1 py-4 font-bold text-white bg-emerald-600 rounded-xl shadow-lg shadow-emerald-200">Create System</button>
            </div>
          </div>
        </div>
      )}
    </main>
  );
}
